# This file is autogenerated by the hrpc compiler
import compact_encoding as c
from bare_rpc import RPC


class HRPC:
    def __init__(self, send, resolve):
        self._handlers = {}
        self._request_codecs = {
            0: resolve("@test/req"),
            1: c.string,
        }
        self._response_codecs = {
            0: resolve("@test/res"),
        }
        self._rpc = RPC(send, on_request=self._on_request, on_event=self._on_event)

    async def receive(self, data):
        await self._rpc.receive(data)

    async def command_a(self, request=None):
        data = None if request is None else c.encode(self._request_codecs[0], request)
        raw = await self._rpc.request(0, data)
        return None if raw is None else c.decode(self._response_codecs[0], raw)

    def on_command_a(self, handler):
        self._handlers[0] = handler

    async def notify(self, request=None):
        data = None if request is None else c.encode(self._request_codecs[1], request)
        await self._rpc.event(1, data)

    def on_notify(self, handler):
        self._handlers[1] = handler

    async def _on_request(self, req):
        handler = self._handlers.get(req.command)
        if handler is None:
            return
        request = None if not req.data else c.decode(self._request_codecs[req.command], req.data)
        response = await handler(request)
        data = None if response is None else c.encode(self._response_codecs[req.command], response)
        await req.reply(data)

    async def _on_event(self, ev):
        handler = self._handlers.get(ev.command)
        if handler is None:
            return
        request = None if not ev.data else c.decode(self._request_codecs[ev.command], ev.data)
        await handler(request)
