const errors = require('./errors')

const VALID_HANDLER_NAME = /^@[a-z][a-z0-9-]*\/[a-z][a-z0-9-]*$/

const PRIMITIVES = {
  uint: 'c.uint',
  uint32: 'c.uint32',
  int: 'c.int',
  string: 'c.string',
  buffer: 'c.buffer'
}

const PYTHON_KEYWORDS = new Set([
  'False',
  'None',
  'True',
  'and',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'try',
  'while',
  'with',
  'yield'
])

module.exports = function generatePython(hrpc) {
  const seen = new Set(['receive'])
  let usesResolve = false
  const commands = []

  for (const h of hrpc.handlers) {
    if (!VALID_HANDLER_NAME.test(h.name)) {
      throw errors.INVALID_HANDLER_NAME(
        `Invalid handler name '${h.name}', names must match @namespace/kebab-name`
      )
    }
    const method = toMethodName(h.name)
    if (PYTHON_KEYWORDS.has(method)) {
      throw errors.RESERVED_KEYWORD(
        `Handler '${h.name}' maps to Python keyword '${method}', rename the handler`
      )
    }
    if (seen.has(method)) {
      throw errors.DUPLICATE_METHOD_NAME(
        `Handlers produce duplicate Python method name '${method}'`
      )
    }
    seen.add(method)

    const registration = 'on_' + method
    if (seen.has(registration)) {
      throw errors.DUPLICATE_METHOD_NAME(
        `Handler '${h.name}' produces registration method '${registration}' that collides with another handler or a reserved method`
      )
    }
    seen.add(registration)

    const hasResponse = h.response !== undefined && h.response !== null
    const reqStream = h.request.stream === true
    const respStream = hasResponse && h.response.stream === true
    const isSend = h.request.send === true && !hasResponse

    if (reqStream) {
      throw errors.UNSUPPORTED_HANDLER(
        `Handler '${h.name}' uses streams, which are not supported yet`
      )
    }

    let kind
    if (respStream) {
      kind = 'response-stream'
    } else if (isSend) {
      kind = 'send'
    } else if (hasResponse) {
      kind = 'normal'
    } else {
      throw errors.MISSING_RESPONSE(
        `Handler '${h.name}' has no response; add a response or set request.send: true`
      )
    }

    const req = codecExpr(h.request.name)
    if (req.usesResolve) usesResolve = true
    let respCodec = null
    if (kind !== 'send') {
      const resp = codecExpr(h.response.name)
      if (resp.usesResolve) usesResolve = true
      respCodec = resp.expr
    }

    commands.push({ id: h.id, method, kind, reqCodec: req.expr, respCodec })
  }

  const hasResponseStream = commands.some((c) => c.kind === 'response-stream')
  const hasRequestStream = commands.some((c) => c.kind === 'request-stream')
  const hasDuplex = commands.some((c) => c.kind === 'duplex')
  const hasStream = hasResponseStream || hasRequestStream || hasDuplex

  const lines = [
    '# This file is autogenerated by the hrpc compiler',
    'import compact_encoding as c'
  ]
  lines.push(hasStream ? 'from bare_rpc import RPC, RPCRemoteError' : 'from bare_rpc import RPC')
  lines.push('')
  if (hasStream) lines.push(...streamWrapperClasses(), '')
  lines.push(
    '',
    'class HRPC:',
    usesResolve ? '    def __init__(self, send, resolve):' : '    def __init__(self, send):',
    '        self._handlers = {}'
  )

  emitDict(
    lines,
    '_request_codecs',
    commands.map((c) => [c.id, c.reqCodec])
  )
  emitDict(
    lines,
    '_response_codecs',
    commands.filter((c) => c.kind !== 'send').map((c) => [c.id, c.respCodec])
  )

  if (hasResponseStream) {
    emitSet(
      lines,
      '_response_stream_commands',
      commands.filter((c) => c.kind === 'response-stream').map((c) => c.id)
    )
  }
  if (hasRequestStream) {
    emitSet(
      lines,
      '_request_stream_commands',
      commands.filter((c) => c.kind === 'request-stream').map((c) => c.id)
    )
  }
  if (hasDuplex) {
    emitSet(
      lines,
      '_duplex_commands',
      commands.filter((c) => c.kind === 'duplex').map((c) => c.id)
    )
  }

  lines.push(
    '        self._rpc = RPC(send, on_request=self._on_request, on_event=self._on_event)',
    '',
    '    async def receive(self, data):',
    '        await self._rpc.receive(data)',
    ''
  )

  for (const cmd of commands) lines.push(...generateMethods(cmd))

  if (hasRequestStream) {
    lines.push(
      '    async def _await_response(self, command, future):',
      '        raw = await future',
      '        return None if raw is None else c.decode(self._response_codecs[command], raw)',
      ''
    )
  }

  lines.push(...generateOnRequest({ hasResponseStream, hasRequestStream, hasDuplex }))
  lines.push('')
  if (hasResponseStream) lines.push(...generateResponseStreamDispatch(commands), '')
  if (hasRequestStream) lines.push(...generateRequestStreamDispatch(commands), '')
  if (hasDuplex) lines.push(...generateDuplexDispatch(commands), '')
  lines.push(...generateOnEvent())

  return lines.join('\n') + '\n'
}

function generateMethods(cmd) {
  const lines = []
  if (cmd.kind === 'response-stream') {
    lines.push(`    async def ${cmd.method}(self, request=None):`)
    lines.push(
      `        data = None if request is None else c.encode(self._request_codecs[${cmd.id}], request)`
    )
    lines.push(`        stream = await self._rpc.request_with_response_stream(${cmd.id}, data)`)
    lines.push(`        return _IncomingStream(stream, self._response_codecs[${cmd.id}])`)
  } else {
    lines.push(`    async def ${cmd.method}(self, request=None):`)
    lines.push(
      `        data = None if request is None else c.encode(self._request_codecs[${cmd.id}], request)`
    )
    if (cmd.kind === 'send') {
      lines.push(`        await self._rpc.event(${cmd.id}, data)`)
    } else {
      lines.push(`        raw = await self._rpc.request(${cmd.id}, data)`)
      lines.push(
        `        return None if raw is None else c.decode(self._response_codecs[${cmd.id}], raw)`
      )
    }
  }
  lines.push('')
  lines.push(`    def on_${cmd.method}(self, handler):`)
  lines.push(`        self._handlers[${cmd.id}] = handler`)
  lines.push('')
  return lines
}

function generateOnRequest({ hasResponseStream, hasRequestStream, hasDuplex }) {
  const lines = ['    async def _on_request(self, req):']
  if (hasRequestStream || hasDuplex) {
    lines.push('        if req.request_stream is not None:')
    if (hasDuplex) {
      lines.push(
        '            if req.command in self._duplex_commands:',
        '                return await self._dispatch_duplex(req)'
      )
    }
    if (hasRequestStream) {
      lines.push(
        '            if req.command in self._request_stream_commands:',
        '                return await self._dispatch_request_stream(req)'
      )
    }
    lines.push('            return')
  }
  if (hasResponseStream) {
    lines.push(
      '        if req.command in self._response_stream_commands:',
      '            return await self._dispatch_response_stream(req)'
    )
  }
  lines.push(
    '        handler = self._handlers.get(req.command)',
    '        if handler is None:',
    '            return',
    '        request = None if not req.data else c.decode(self._request_codecs[req.command], req.data)',
    '        response = await handler(request)',
    '        data = None if response is None else c.encode(self._response_codecs[req.command], response)',
    '        await req.reply(data)'
  )
  return lines
}

function generateOnEvent() {
  return [
    '    async def _on_event(self, ev):',
    '        handler = self._handlers.get(ev.command)',
    '        if handler is None:',
    '            return',
    '        request = None if not ev.data else c.decode(self._request_codecs[ev.command], ev.data)',
    '        await handler(request)'
  ]
}

function emitSet(lines, name, ids) {
  lines.push(`        self.${name} = {${ids.join(', ')}}`)
}

function streamWrapperClasses() {
  return [
    'class _OutgoingStream:',
    '    def __init__(self, stream, codec):',
    '        self._stream = stream',
    '        self._codec = codec',
    '',
    '    async def write(self, value):',
    '        await self._stream.write(c.encode(self._codec, value))',
    '',
    '    async def end(self):',
    '        await self._stream.end()',
    '',
    '    async def destroy(self, error=None):',
    '        await self._stream.destroy(error)',
    '',
    '',
    'class _IncomingStream:',
    '    def __init__(self, stream, codec):',
    '        self._stream = stream',
    '        self._codec = codec',
    '',
    '    def __aiter__(self):',
    '        return self',
    '',
    '    async def __anext__(self):',
    '        raw = await self._stream.__anext__()',
    '        return c.decode(self._codec, raw)'
  ]
}

function generateResponseStreamDispatch(commands) {
  const lines = ['    async def _dispatch_response_stream(self, req):']
  lines.push('        handler = self._handlers.get(req.command)')
  lines.push('        if handler is None:')
  lines.push(
    '            await req.reject(RPCRemoteError("No handler registered", "NO_HANDLER", 0))'
  )
  lines.push('            return')
  lines.push('        try:')
  lines.push(
    '            request = None if not req.data else c.decode(self._request_codecs[req.command], req.data)'
  )
  lines.push('        except Exception as exc:')
  lines.push('            await req.reject(RPCRemoteError(str(exc), "DECODE_ERROR", 0))')
  lines.push('            return')
  lines.push(
    '        outgoing = _OutgoingStream(await req.create_response_stream(), self._response_codecs[req.command])'
  )
  lines.push('        try:')
  lines.push('            await handler(request, outgoing)')
  lines.push('        except Exception as exc:')
  lines.push('            await outgoing.destroy(RPCRemoteError(str(exc), "HANDLER_ERROR", 0))')
  return lines
}
function generateRequestStreamDispatch() {
  return []
}
function generateDuplexDispatch() {
  return []
}

function emitDict(lines, name, entries) {
  if (entries.length === 0) {
    lines.push(`        self.${name} = {}`)
    return
  }
  lines.push(`        self.${name} = {`)
  for (const [k, v] of entries) lines.push(`            ${k}: ${v},`)
  lines.push('        }')
}

function toMethodName(fqn) {
  return fqn
    .slice(fqn.indexOf('/') + 1)
    .split('-')
    .join('_')
}

function codecExpr(typeName) {
  if (PRIMITIVES[typeName]) return { expr: PRIMITIVES[typeName], usesResolve: false }
  if (typeName.includes('/')) {
    return { expr: `resolve(${JSON.stringify(typeName)})`, usesResolve: true }
  }
  throw errors.UNSUPPORTED_TYPE(`Unsupported type '${typeName}'`)
}
