const errors = require('./errors')

const VALID_HANDLER_NAME = /^@[a-z][a-z0-9-]*\/[a-z][a-z0-9-]*$/

const PRIMITIVES = {
  uint: 'c.uint',
  uint32: 'c.uint32',
  int: 'c.int',
  string: 'c.string',
  buffer: 'c.buffer'
}

const PYTHON_KEYWORDS = new Set([
  'False',
  'None',
  'True',
  'and',
  'as',
  'assert',
  'async',
  'await',
  'break',
  'class',
  'continue',
  'def',
  'del',
  'elif',
  'else',
  'except',
  'finally',
  'for',
  'from',
  'global',
  'if',
  'import',
  'in',
  'is',
  'lambda',
  'nonlocal',
  'not',
  'or',
  'pass',
  'raise',
  'return',
  'try',
  'while',
  'with',
  'yield'
])

module.exports = function generatePython(hrpc) {
  const seen = new Set()
  let usesResolve = false
  const commands = []

  for (const h of hrpc.handlers) {
    if (!VALID_HANDLER_NAME.test(h.name)) {
      throw errors.INVALID_HANDLER_NAME(
        `Invalid handler name '${h.name}', names must match @namespace/kebab-name`
      )
    }
    const method = toMethodName(h.name)
    if (PYTHON_KEYWORDS.has(method)) {
      throw errors.RESERVED_KEYWORD(
        `Handler '${h.name}' maps to Python keyword '${method}', rename the handler`
      )
    }
    if (seen.has(method)) {
      throw errors.DUPLICATE_METHOD_NAME(
        `Handlers produce duplicate Python method name '${method}'`
      )
    }
    seen.add(method)

    if (h.request.stream === true || (h.response && h.response.stream === true)) {
      throw errors.UNSUPPORTED_HANDLER(
        `Handler '${h.name}' uses streams, which are not supported yet`
      )
    }
    const hasResponse = h.response !== undefined && h.response !== null
    const isSend = h.request.send === true && !hasResponse
    if (!isSend && !hasResponse) {
      throw errors.MISSING_RESPONSE(
        `Handler '${h.name}' has no response; add a response or set request.send: true`
      )
    }

    const req = codecExpr(h.request.name)
    if (req.usesResolve) usesResolve = true
    let resp = null
    if (!isSend) {
      resp = codecExpr(h.response.name)
      if (resp.usesResolve) usesResolve = true
    }
    commands.push({
      id: h.id,
      method,
      isSend,
      reqCodec: req.expr,
      respCodec: resp ? resp.expr : null
    })
  }

  const lines = [
    '# This file is autogenerated by the hrpc compiler',
    'import compact_encoding as c',
    'from bare_rpc import RPC',
    '',
    '',
    'class HRPC:',
    usesResolve ? '    def __init__(self, send, resolve):' : '    def __init__(self, send):',
    '        self._handlers = {}'
  ]

  emitDict(
    lines,
    '_request_codecs',
    commands.map((c) => [c.id, c.reqCodec])
  )
  emitDict(
    lines,
    '_response_codecs',
    commands.filter((c) => !c.isSend).map((c) => [c.id, c.respCodec])
  )

  lines.push(
    '        self._rpc = RPC(send, on_request=self._on_request, on_event=self._on_event)',
    '',
    '    async def receive(self, data):',
    '        await self._rpc.receive(data)',
    ''
  )

  for (const cmd of commands) {
    lines.push(`    async def ${cmd.method}(self, request=None):`)
    lines.push(
      `        data = None if request is None else c.encode(self._request_codecs[${cmd.id}], request)`
    )
    if (cmd.isSend) {
      lines.push(`        await self._rpc.event(${cmd.id}, data)`)
    } else {
      lines.push(`        raw = await self._rpc.request(${cmd.id}, data)`)
      lines.push(
        `        return None if raw is None else c.decode(self._response_codecs[${cmd.id}], raw)`
      )
    }
    lines.push('')
    lines.push(`    def on_${cmd.method}(self, handler):`)
    lines.push(`        self._handlers[${cmd.id}] = handler`)
    lines.push('')
  }

  lines.push(
    '    async def _on_request(self, req):',
    '        handler = self._handlers.get(req.command)',
    '        if handler is None:',
    '            return',
    '        request = None if not req.data else c.decode(self._request_codecs[req.command], req.data)',
    '        response = await handler(request)',
    '        data = None if response is None else c.encode(self._response_codecs[req.command], response)',
    '        await req.reply(data)',
    '',
    '    async def _on_event(self, ev):',
    '        handler = self._handlers.get(ev.command)',
    '        if handler is None:',
    '            return',
    '        request = None if not ev.data else c.decode(self._request_codecs[ev.command], ev.data)',
    '        await handler(request)'
  )

  return lines.join('\n') + '\n'
}

function emitDict(lines, name, entries) {
  if (entries.length === 0) {
    lines.push(`        self.${name} = {}`)
    return
  }
  lines.push(`        self.${name} = {`)
  for (const [k, v] of entries) lines.push(`            ${k}: ${v},`)
  lines.push('        }')
}

function toMethodName(fqn) {
  return fqn
    .slice(fqn.indexOf('/') + 1)
    .split('-')
    .join('_')
}

function codecExpr(typeName) {
  if (PRIMITIVES[typeName]) return { expr: PRIMITIVES[typeName], usesResolve: false }
  if (typeName.includes('/')) {
    return { expr: `resolve(${JSON.stringify(typeName)})`, usesResolve: true }
  }
  throw errors.UNSUPPORTED_TYPE(`Unsupported type '${typeName}'`)
}
